### ISSUE TITLE
Background not shown in Android

### ISSUE THREAD

**Issue by bagusflyer** [browniefed/react-native-screens#1]
I tried your code in android. But the background image is not shown in android if I use local image.

`<Image style={styles.bg} source={require('./background.png')} />` 

Also the lines or shown for text input in android so that it's duplicated.

![screen shot 2016-01-21 at 5 43 40 pm](https://cloud.githubusercontent.com/assets/1187737/12476799/a109df58-c066-11e5-85be-7a8115956c14.png)

What's the difference between ios and android? Thanks

**Comment by bhdrk** [comment]
+1

**Comment by jlugner** [comment]
Not sure about the background, but to remove the lines shown, you can simply add underlineColorAndroid='transparent' 
as a property on your TextInputs.

**Comment by browniefed** [comment]
Sorry I haven't maintained this project. 
Soon I'll be setting up a new organization to build out RN examples, libraries, and demos. So sit tight.

**Comment by jlugner** [comment]
@browniefed Figured, still felt it might be a good comment and suggest possible solutions to existing issues, in case other people get the same errors :)

**Comment by browniefed** [comment]
Thanks, I appreciate it. I'll take a look at incorporating this when I get some time tonight

**Comment by Monte9** [comment]
@bagusflyer @browniefed @Pungsnigel I update the code for RN 0.37 and also updated all the views with flex. Check out issue #3 for the updated code with screenshots on various devices.

**Comment by browniefed** [comment]
Updated to latest
