### ISSUE TITLE
Sign Up screen

### ISSUE THREAD

**Issue by sibelius** [browniefed/react-native-screens#2]
This repo could help people figure it out how to solve some common layout problems.

Create Sign Up screen

![screen-1-2-sign-up](https://cloud.githubusercontent.com/assets/2005841/12485064/2f09d466-c044-11e5-9666-787110be3ce3.jpg)

**Comment by Monte9** [comment]
Second this. ☝
Would be awesome to have the sign-up screen as well.

**Comment by sibelius** [comment]
I think it is better to implement yourself using hotreload on react native to learn better

**Comment by Monte9** [comment]
@sibelius Check out issue #3. I updated the login screen to work with the latest RN and also using flex. I like this project. I think I might implement this myself and create a repo in case anyone else wants to use it. 

Although do you think I should use `react-native-router-flux` to navigate between the two screens or should I make then independent views so that it's drag and drop? Just curious.

**Comment by browniefed** [comment]
Haven't been maintaining this but per my recent exploration into screencasting, showing how to build these types of screens could be fun. I'll update this repo with latest code this weekend

**Comment by sibelius** [comment]
@Monte9 use ex-navigation for navigation

**Comment by Monte9** [comment]
@sibelius finally got around to implementing this screen. What do you think? 
/cc @browniefed 
<img width="500" height="888" alt="screen shot 2016-11-22 at 10 13 14 pm" src="https://cloud.githubusercontent.com/assets/7840686/21176005/cf57f28e-c199-11e6-850d-0eaa947205a8.png">

**Comment by sibelius** [comment]
Looks good!

We can still improve a little bit

Use the font of the design
Fix image
Fix spacing issues

**Comment by browniefed** [comment]
Happy to accept a PR, I've updated the login page w/ working code for latest RN

**Comment by Monte9** [comment]
@browniefed ok, i'll submit a PR soon. Do you plan to work on any of the other screens?

**Comment by browniefed** [comment]
I'll likely be spinning up new screens, and showing how to build them on `egghead` so this project actually may become a priority now.

**Comment by Monte9** [comment]
@browniefed I have been working on a new RN Starter project. Would love your feedback on it. 
https://github.com/Monte9/react-native-starter
/cc @sibelius
